# Documentation:
# https://github.com/trovu/trovu.github.io/wiki/Advanced-settings-&-personal-shortcuts#custom-configuration
namespaces:
- o
- de
- .de
- sthuebner
- github: .
defaultKeyword: k
language: de
country: de
